### ISSUE TITLE
Enterprise Tier not listed

### ISSUE THREAD

**Issue by eaball35** [googleapis/java-filestore#130]
b/217532386

"A customer told me they can see tier=6 with enterprise instances, but this is not translated by the enum since it only contains the values until 5. https://cloud.google.com/java/docs/reference/google-cloud-filestore/latest/com.google.cloud.filestore.v1.Instance.Tier"

https://github.com/googleapis/java-filestore/blob/main/proto-google-cloud-filestore-v1/src/main/proto/google/cloud/filestore/v1/cloud_filestore_service.proto#L350

**Comment by suztomo** [comment]
It now exists

![image](https://user-images.githubusercontent.com/28604/236533300-4b1d4225-87a6-45d4-b308-6c23dbcd7057.png)
